chat_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

coaching_app/urls.py
from django.urls import path
from . import views
from .api import StudentList, CoachList, TeamList, TeamDetail

app_name = 'coaching_app'

urlpatterns = [
    path('', views.index, name='index'),
    
    # #students path
    # path('students/', views.student_list, name='student_list'),
    # path('students/<int:pk>', views.student_detail, name='student_detail'),

    # #coaches path
    # path('coaches/', views.coach_list, name='coach_list'),

    # teams path
    path('team/<int:pk>', views.team_view, name='team_view'),
    path('team/create', views.team_create, name='team_create'),
    path('team/<int:pk>/insert', views.team_insert, name='team_insert'),
    path('team/<int:pk>/kick', views.team_kick, name='team_kick'),
    path('team/<int:pk>/settings', views.team_settings, name='team_settings'),
    path('team/<int:pk>/settings/update', views.team_update, name='team_update'),
    path('team/<int:pk>/settings/delete', views.team_delete, name='team_delete'),
    # path('team/<int:pk>/insert_coach', views.team_insert_coach, name='team_insert_coach'),

    #api
    path('api/v1/students', StudentList.as_view()),
    path('api/v1/students/<int:pk>', StudentList.as_view()),

    path('api/v1/coaches', CoachList.as_view()),
    path('api/v1/coaches/<int:pk>', CoachList.as_view()),

    path('api/v1/teams', TeamList.as_view()),
    path('api/v1/teams/<int:pk>', TeamDetail.as_view()),
]

coaching_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coaching_app.urls')),
    path('account/', include('login_app.urls')),
    path('chat/', include('chat_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('request_password_reset/', views.request_password_reset, name='request_password_reset'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('delete_account/', views.delete_account, name='delete_account'),
    path('change_password/', views.change_password, name='change_password'),
]

coaching_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Tag(models.Model):
    tagname = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.tagname}"

class Stat(models.Model):
    statname = models.CharField(max_length=200)
    statvalue = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.statname} {self.statvalue}"

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    stat = models.ManyToManyField(Stat)

    def __str__(self):
        return f"{self.user}"

class Coach(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)
    def __str__(self):
        return f"{self.user}"

class Team(models.Model):
    name = models.CharField(max_length=200)
    student = models.ManyToManyField(Student)
    coach = models.ManyToManyField(Coach)

    def __str__(self):
        return f"Team {self.id}"

coaching_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Student, Coach, Tag, Team
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required

@login_required(login_url='/account/login/')
def index(request):
    print(request)

    if Coach.objects.filter(user = request.user):
        my_teams = Team.objects.filter(coach__user = request.user)
        context = {
            'my_teams': my_teams
        }
        return render(request, 'coaching_app/index.html', context)

    elif Student.objects.filter(user = request.user):
        my_teams = Team.objects.filter(student__user = request.user)
        print(my_teams)
        context = {
            'my_teams': my_teams
        }
        return render(request, 'coaching_app/index.html', context)
    return render(request, 'coaching_app/index.html')

@login_required(login_url='/account/login/')
def team_create(request):
    if request.method== "POST":
        coach = Coach.objects.get(user = request.user)

        team_name = request.POST["team_name"]
        team = Team()
        team.name = team_name
        team.save()
        team.coach.add(coach)
        team.save()

        return redirect('coaching_app:team_view', pk=team.pk)
    return render(request, 'coaching_app/team_create.html')

@login_required(login_url='/account/login/')
def team_view(request, pk):
    team = get_object_or_404(Team, pk=pk)
    
    # Get the coaches and students
    coaches = team.coach.all()
    students = team.student.all()

    if not Coach.objects.get(user = request.user) == None:
        print("this is coach")

    elif not Student.objects.get(user = request.user) == None:
        print("this is student")

    context = {
        'team': team,
        'coaches': coaches,
        'students': students
    }
    return render(request, 'coaching_app/team_view.html', context)

@login_required(login_url='/account/login/')
def team_insert(request, pk):
    team = get_object_or_404(Team, pk=pk)

    if request.method == "POST":
        if 'student_pk' in request.POST:
            student_pk = request.POST["student_pk"]
            student = get_object_or_404(Student, pk=student_pk)
            team.student.add(student)

        elif 'coach_pk' in request.POST:
            coach_pk = request.POST["coach_pk"]
            coach = get_object_or_404(Coach, pk=coach_pk)
            team.coach.add(coach)

    return redirect('coaching_app:team_settings', pk=team.pk)

@login_required(login_url='/account/login/')
def team_kick(request, pk):
    team = get_object_or_404(Team, pk=pk)
    
    if request.method == "POST":
        if 'student_pk' in request.POST:
            student_pk = request.POST["student_pk"]
            student = get_object_or_404(Student, pk=student_pk)
            team.student.remove(student)

        elif 'coach_pk' in request.POST:
            coach_pk = request.POST["coach_pk"]
            coach = get_object_or_404(Coach, pk=coach_pk)
            team.coach.remove(coach)

    return redirect('coaching_app:team_view', pk=team.pk)

def team_settings(request, pk):
    team = get_object_or_404(Team, pk=pk)
    
    # Get the coaches and students
    coaches = team.coach.all()
    students = team.student.all()

    # Get the coaches and students not in this room
    students_not_in_team = Student.objects.filter().exclude(team__pk = pk)
    coaches_not_in_team = Coach.objects.filter().exclude(team__pk = pk)

    if not Coach.objects.get(user = request.user) == None:
        print("this is coach")

    elif not Student.objects.get(user = request.user) == None:
        print("this is student")

    context = {
        'team': team,
        'coaches': coaches,
        'students': students,
        'studentsAdd': students_not_in_team,
        'coachesAdd': coaches_not_in_team
    }
    return render(request, 'coaching_app/team_settings.html', context)

def team_delete(request, pk):
    team = get_object_or_404(Team, pk=pk)

    if request.method == "POST":
        if request.POST['delete'] == "DELETE":
            team.delete()
            return redirect('coaching_app:index')
    return redirect('coaching_app:team_settings', pk=team.pk)

def team_update(request, pk):
    team = get_object_or_404(Team, pk=pk)
    
    if request.method == "POST":
        updated_name = request.POST['team']
        team.update(name = updated_name)
        return redirect('coaching_app:team_view', pk=team.pk)
    return redirect('coaching_app:team_settings', pk=team.pk)
    

        
                

coaching_app/templates/coaching_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coaching || Frontpage</title>
</head>

<body>
    <h1>This is my coaching platform</h1>
    <div>
        <nav>
            <ul>
                <li><a href="{% url 'coaching_app:team_create' %}">Create a team</a></li>
                <li><a href="{% url 'login_app:logout' %}">Logout</a></li>
                <li><a href="{% url 'login_app:change_password' %}">Change password</a></li>
            </ul>
            <nav>
    </div>
    <h3>{{ user.username|title }} teams:</h3>
    {% for team in my_teams %}
    <div>
        {{ team.name }}
        {% comment %} <a href="{% url "coaching_app:team_view" %}">Go</a> {% endcomment %}
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" value="{{team.pk}}">
            <button formaction="{% url 'coaching_app:team_view' team.pk %}">Go</button>
        </form>

    </div>
    {% endfor %}

</body>

</html>

coaching_app/templates/coaching_app/team_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coaching || Create a team</title>
</head>

<body>
    <h1>Create a team</h1>
    <div>
        <form method="POST">
            {% csrf_token %}
            <input type="text" name="team_name" placeholder="Name">
            <button formaction="{% url 'coaching_app:team_create' %}">Create!</button>
        </form>
    </div>
</body>

</html>

coaching_app/templates/coaching_app/team_settings.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ team.name|title }}</title>
</head>

<body>
    <h1>Settings for: {{ team.name|title }}</h1>

    <div>Update the team name
        <form action="{% url 'coaching_app:team_update' team.pk %}" method="POST">
            {% csrf_token %}
            <input type="text" name="update" placeholder="New team name">
            <button>Update</button>
        </form>
    </div>

        <div>
        <div>This is the students:</div>
        {% for student in students %}
        <div>
            <form action="{% url 'coaching_app:team_kick' team.pk %}" method="POST">
                {% csrf_token %}
                {{ student.user.username }}
                <button>Kick</button>
                <input type="hidden" name="student_pk" value="{{ student.pk }}">
            </form>
        </div>
        {% endfor %}
    </div>

    <div>
        <div>Add students to the team</div>
        {% for studentAdd in studentsAdd %}
        <div>
            <form action="{% url 'coaching_app:team_insert' team.pk %}" method="POST">
                {% csrf_token %}
                {{ studentAdd.user.username }}
                <button>Add</button>
                <input type="hidden" name="student_pk" value="{{ studentAdd.pk }}">
            </form>
        </div>
        {% endfor %}
    </div>

    <div>
        <div>This is the coaches:</div>

        {% for coach in coaches %}
        <div>
            <form action="{% url 'coaching_app:team_kick' team.pk %}" method="POST">
                {% csrf_token %}
                {{ coach.user.username }}
                <button>Kick</button>
                <input type="hidden" name="coach_pk" value="{{ coach.pk }}">
            </form>
        </div>
        {% endfor %}
    </div>

    <div>
        <div>Add coaches to the team</div>
        {% for coachAdd in coachesAdd %}
        <div>
            <form action="{% url 'coaching_app:team_insert' team.pk %}" method="POST">
                {% csrf_token %}
                {{ coachAdd.user.username }}
                <button>Add</button>
                <input type="hidden" name="coach_pk" value="{{ coachAdd.pk }}">
            </form>
        </div>
        {% endfor %}
    </div>

    <form action="{% url 'coaching_app:team_delete' team.pk %}" method="POST">
        {% csrf_token %}
        <div>Type "DELETE" to delete</div>
        <input type="text" name="delete" placeholder="DELETE">
        <button>Delete team</button>
    </form>
</body>

</html>

coaching_app/templates/coaching_app/team_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coaching || {{ team.name }}</title>
</head>

<body>
    <h1>This team is : {{ team.name|title }}</h1>
    <a href="{% url 'coaching_app:index' %}">Go to frontpage</a>
    <form action="{% url 'coaching_app:team_settings' team.pk %}" method="POST">
        {% csrf_token %}
        <button>Settings</button>
    </form>


    <div>
        <div>This is the coaches:</div>
        {% for coach in coaches %}
            <div>{{coach.user.username}}</div>
        {% endfor %}
    </div>
    
    <div>
        <div>This is the students:</div>
        {% for student in students %}
            <div>{{student.user.username}}</div>
        {% for tag in students_tag %}
            <div>{{ tag.tagname }}</div>
        {% endfor %}
        {% endfor %}
    </div>
</body>

</html>